services:
 app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${RHOST}
      - REDIS_PORT=${RPORT}
    restart: always
 redis:
    image: "redis:alpine"